
# Use root/example as user/password credentials
version: '3.1'

services:

    php-apache:
        image: php:7.2.1-apache
        ports:
            - 8080:80
        volumes:
            - ./DocumentRoot:/var/www/html:z
        links:
            - 'db'

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - db
        depends_on:
          - db
        ports:
          - "4002:80"

volumes:
    db:

