version: '2'

services:
  myapp:
    image: bitnami/symfony:1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './myapp:/app/myapp'      
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=tables
      - MARIADB_DATABASE=myapp
    depends_on:
      - mariadb
    links:
      - mariadb  
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=tables
      - MARIADB_DATABASE=myapp